//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uprise {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uprise.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що ми викладаєм?.
        /// </summary>
        public static string AnsTeach {
            get {
                return ResourceManager.GetString("AnsTeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Арт-школа.
        /// </summary>
        public static string ArtSchool {
            get {
                return ResourceManager.GetString("ArtSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Рівне вул.Д.Галицького, 19, офіс 910
        ///(9 поверх).
        /// </summary>
        public static string City1 {
            get {
                return ResourceManager.GetString("City1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Сарни вул.Широка, 1 (2 поверх).
        /// </summary>
        public static string City2 {
            get {
                return ResourceManager.GetString("City2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to смт.Клесів вул.Чайковського, 1.
        /// </summary>
        public static string City3 {
            get {
                return ResourceManager.GetString("City3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Рокитне вул.Шевченка, 1(приміщення стоматології, 2-й поверх).
        /// </summary>
        public static string City4 {
            get {
                return ResourceManager.GetString("City4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Володимирець вул.Соборна 1 (приміщення кафе &quot;Чилі&quot;, 3-й поверх).
        /// </summary>
        public static string City5 {
            get {
                return ResourceManager.GetString("City5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Дубровиця вул.Поштова, 2 (вхід збоку, 2-й поверх).
        /// </summary>
        public static string City6 {
            get {
                return ResourceManager.GetString("City6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Вараш м-н Вараш, 43.
        /// </summary>
        public static string City7 {
            get {
                return ResourceManager.GetString("City7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Березне вул. Андріївська, 15а(3-й поверх).
        /// </summary>
        public static string City8 {
            get {
                return ResourceManager.GetString("City8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Олевськ вул. Привокзальна, 8(ТЦ &quot;Life House&quot;, 3-й поверх).
        /// </summary>
        public static string City9 {
            get {
                return ResourceManager.GetString("City9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курси.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З ПН-ПТ 9:00 по 19:00.
        /// </summary>
        public static string Data1 {
            get {
                return ResourceManager.GetString("Data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В суботу з 10:00 по 15:00.
        /// </summary>
        public static string Data2 {
            get {
                return ResourceManager.GetString("Data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська мова.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перше заняття безкоштовне.
        /// </summary>
        public static string FistFree {
            get {
                return ResourceManager.GetString("FistFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі права захищені | Цей сайт створений з.
        /// </summary>
        public static string Footer1 {
            get {
                return ResourceManager.GetString("Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to командою VlAndr.
        /// </summary>
        public static string Footer2 {
            get {
                return ResourceManager.GetString("Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ваше ім&apos;я та призвіще.
        /// </summary>
        public static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть вашу пошту.
        /// </summary>
        public static string Form2 {
            get {
                return ResourceManager.GetString("Form2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть тему повідомлення.
        /// </summary>
        public static string Form3 {
            get {
                return ResourceManager.GetString("Form3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст повідомлення.
        /// </summary>
        public static string Form4 {
            get {
                return ResourceManager.GetString("Form4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити повідомлення.
        /// </summary>
        public static string Form5 {
            get {
                return ResourceManager.GetString("Form5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дізнатися більше.
        /// </summary>
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ми гарантуємо якісне та цікаве навчання!.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to це майданчик альтернативної освіти, який дозволить учням розвинути в собі різна практичні навики та креативне мислення.
        /// </summary>
        public static string HomeTitle2 {
            get {
                return ResourceManager.GetString("HomeTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to це різноплановий центр, який включає різні напрямки освіти відповідно до вимог сучасного світу..
        /// </summary>
        public static string HomeTitle3 {
            get {
                return ResourceManager.GetString("HomeTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наші викладачі - це молода команда висококваліфікованих професіоналів, які люблять і живуть своєю роботою..
        /// </summary>
        public static string HomeTitle4 {
            get {
                return ResourceManager.GetString("HomeTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підготовка до школи.
        /// </summary>
        public static string PreparSchool {
            get {
                return ResourceManager.GetString("PreparSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Програмування &amp; Дизайн.
        /// </summary>
        public static string ProgrammingAndDesign {
            get {
                return ResourceManager.GetString("ProgrammingAndDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправ нам лист в любий час.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лісничик Ольга Сергіївна.
        /// </summary>
        public static string Teacher1 {
            get {
                return ResourceManager.GetString("Teacher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Козел Жанна Петрівна.
        /// </summary>
        public static string Teacher10 {
            get {
                return ResourceManager.GetString("Teacher10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скобайло Любов Романівна.
        /// </summary>
        public static string Teacher11 {
            get {
                return ResourceManager.GetString("Teacher11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балаушко Юлія Василівна.
        /// </summary>
        public static string Teacher12 {
            get {
                return ResourceManager.GetString("Teacher12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корнелюк Леся Миколаївна.
        /// </summary>
        public static string Teacher13 {
            get {
                return ResourceManager.GetString("Teacher13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кахан Любов Володимирівна.
        /// </summary>
        public static string Teacher14 {
            get {
                return ResourceManager.GetString("Teacher14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паньковець Ірина Леонідівна.
        /// </summary>
        public static string Teacher15 {
            get {
                return ResourceManager.GetString("Teacher15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стельмах Мирослава Василівна.
        /// </summary>
        public static string Teacher16 {
            get {
                return ResourceManager.GetString("Teacher16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Савчук Наталія Олександрівна.
        /// </summary>
        public static string Teacher2 {
            get {
                return ResourceManager.GetString("Teacher2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ганчук Антоніна Миколаївна.
        /// </summary>
        public static string Teacher3 {
            get {
                return ResourceManager.GetString("Teacher3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юсенко Катерина Іванівна.
        /// </summary>
        public static string Teacher4 {
            get {
                return ResourceManager.GetString("Teacher4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шиш Тетяна Валеріївна.
        /// </summary>
        public static string Teacher5 {
            get {
                return ResourceManager.GetString("Teacher5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Харипончук Лілія Володимирівна.
        /// </summary>
        public static string Teacher6 {
            get {
                return ResourceManager.GetString("Teacher6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турлай Адріана Ігорівна.
        /// </summary>
        public static string Teacher7 {
            get {
                return ResourceManager.GetString("Teacher7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Косовська Тетяна  Ігорівна.
        /// </summary>
        public static string Teacher8 {
            get {
                return ResourceManager.GetString("Teacher8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наумчук Юлія Олегівна.
        /// </summary>
        public static string Teacher9 {
            get {
                return ResourceManager.GetString("Teacher9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач художнього класу.
        /// </summary>
        public static string TeacherArtTitle {
            get {
                return ResourceManager.GetString("TeacherArtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач англійської мови.
        /// </summary>
        public static string TeacherEnglishTitle {
            get {
                return ResourceManager.GetString("TeacherEnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наші викладачі.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to це - мережа освітніх центрів, яка включає в себе різні напрямки освіти відповідно до вимог сучасного світу. На даний момент ми присутні у 9 містах, але наша кількість &lt;strong&gt;постійно динамічно зростає .&lt;/strong&gt;
        ///     &lt;br/&gt; &amp;#160; &amp;#160; &amp;#160; Девіз нашої мережі - &quot;Давайте зростати разом! Ваші можливості - безмежні.
        ///     &lt;br/&gt; &amp;#160; &amp;#160; &amp;#160;Наша мета - підняття загального освітнього та культурного рівня дітей та дорослих в регіонах. А також &lt;strong&gt;навчити використовувати сучасні інструменти&lt;/stron [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextCenter {
            get {
                return ResourceManager.GetString("TextCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Коли вчитися цікаво та комфортно, то й результати навчання позитивні та видні!&lt;/strong&gt;.
        /// </summary>
        public static string TextCenter2 {
            get {
                return ResourceManager.GetString("TextCenter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to майданчик альтернативної освіти для тих, хто хоче йти в ногу із вимогами сучасного світу..
        /// </summary>
        public static string TitleAbout1 {
            get {
                return ResourceManager.GetString("TitleAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівненська область.
        /// </summary>
        public static string TitleContact1 {
            get {
                return ResourceManager.GetString("TitleContact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зворотній зв&apos;язок.
        /// </summary>
        public static string TitleContact2 {
            get {
                return ResourceManager.GetString("TitleContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Житомирська область.
        /// </summary>
        public static string TitleContact3 {
            get {
                return ResourceManager.GetString("TitleContact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наші курси.
        /// </summary>
        public static string TitleCourses1 {
            get {
                return ResourceManager.GetString("TitleCourses1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська для дорослих.
        /// </summary>
        public static string TitleEngish4 {
            get {
                return ResourceManager.GetString("TitleEngish4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська для будь-якого віку.
        /// </summary>
        public static string TitleEnglish {
            get {
                return ResourceManager.GetString("TitleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дітей молодшого шкільного віку (1-4 клас).
        /// </summary>
        public static string TitleEnglish1 {
            get {
                return ResourceManager.GetString("TitleEnglish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для дітей дошкільного віку(4-6 років).
        /// </summary>
        public static string TitleEnglish2 {
            get {
                return ResourceManager.GetString("TitleEnglish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підготовка дітей до ЗНО (9-11 клас).
        /// </summary>
        public static string TitleEnglish3 {
            get {
                return ResourceManager.GetString("TitleEnglish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда професіоналів, які сумлінно виконують свою роботу. Мають великий досвід у роботі з дітьми да дорослими..
        /// </summary>
        public static string TitleTeam1 {
            get {
                return ResourceManager.GetString("TitleTeam1", resourceCulture);
            }
        }
    }
}
